### ISSUE TITLE
[Back & Front] 진척사항

### ISSUE THREAD

**Issue by sukyoujin** [qus0in/TeamProject_TravelingByRote#15]
1. 경원팀 진척사항:
FailView & Handler 구현 by 경원: 오류 발생 문제 봉착, 오늘 내 해결 예정
View단에 쿠키정보 띄우기 by 세영: 구현 완료(팝업창 & 화면표시 둘다 가능)

2. 유진팀 진척사항:
user update
메뉴 버튼 기능 연결 및 세부사항 수정

3. 인스타그램 검색 이슈:
타입별 & 지역 지향 (별도 선택)

**Comment by qus0in** [comment]
10/21 아침 회의 이후 새로 논의 예정
