### ISSUE TITLE
[View] 페이지 구성

### ISSUE THREAD

**Issue by sukyoujin** [qus0in/TeamProject_TravelingByRote#6]
1. 랜딩 페이지 구현 
https://colorlib.com/wp/template/andrea/
https://colorlib.com/wp/template/login-form-v18/

로그인 : 정보 입력 및 전송 -> 메인 페이지
회원가입 : 회원가입 버튼 -> 로그인 -> 메인페이지

2. 메인페이지 네비게이션
홈 버튼
최근 검색 리스트
찜하기 리스트
지역 검색

**Comment by qus0in** [comment]
10.22 논의에서 계속 다룰 예정
